### ISSUE TITLE
Images license

### ISSUE THREAD

**Issue by smolse** [influxdata/branding#1]
Hello. I am going to write and self-publish a book about the TICK stack on leanpub.com and would like to use mascot images from this repo in the cover image. What is the license for those?

**Comment by alexpaxton** [comment]
@smolse I just saw this and will notify the appropriate parties

**Comment by alexpaxton** [comment]
You should be okay so long as you don't modify the mascot images

**Comment by smolse** [comment]
Great, thanks.
